### ISSUE TITLE
Fix: Issue with generator working against classic .NET framework library

### ISSUE THREAD

**Issue by another-guy** [another-guy/CSharpToTypeScript#33]
```
Unhandled Exception: System.IO.FileNotFoundException:
Could not load file or assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
The system cannot find the file specified.

   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimePropertyInfo.get_Signature()
   at System.Reflection.RuntimePropertyInfo.get_PropertyType()
   at CSharpToTypeScript.Core.Translation.Rules.Regular.RegularTypeTranslationContext.ResolveDependencies()
   at CSharpToTypeScript.Program.Main(String[] rawArgs)
   at HRIS.Web.Models.GeneratorCli.Program.Main(String[] rawArgs)
```

**Comment by another-guy** [comment]
More testing is needed around the `Precompiled` assemblies.
